spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: sql$#123TD
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  redis:
    host: localhost
    port: 6379
    timeout: 2000ms

  session:
    store-type: redis
    timeout: 30m
server:
  port: 8080

# Payment Configuration
stripe:
  api-key: sk_test_your_stripe_secret_key_here
  publishable-key: pk_test_your_stripe_publishable_key_here

# Application specific configs
app:
  jwt-secret: 4FlfKplyMPYVocYoPLlOFaeyQa3/m+cyDqDMKg/k0qE=
  jwt-expiration: 86400000

payhere:
  merchant-id: 1231720
  merchant-secret: MzA1MTcyNTgwNTYyNDA5NTMyOTIwMTc5NDc4MzQ3MjMxNjgwODM=
  sandbox-url: https://sandbox.payhere.lk/pay/checkout
  return-url: https://randomid.ngrok.io/payment/success
  cancel-url: https://randomid.ngrok.io/payment/cancel
  notify-url: https://randomid.ngrok.io/payment/notify